### ISSUE TITLE
[bug] Unhandled Exception on whiteListedGames due to incorrect game title

### ISSUE THREAD

**Issue by WesVleuten** [WesVleuten/Servant#36]
Ran command `;config add whiteListedGames BeatSabber`

```
(node:9787) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at TwitchClient.<anonymous> (/home/westar/workspace/Servant/dist/lib/twitch.js:56:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/westar/workspace/Servant/dist/lib/twitch.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9787) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by WesVleuten** [comment]
Seems to be going wrong with even correct input.

Maybe twitch is having issues? Or api change?
